kind = "mariod"
slots = [0,1,2]

[[param_int]]
param = "jump_squat_frame"
subparam = ""
value = 6

[[param_int]]
param = "wall_jump_type"
subparam = ""
value = 0

[[attribute_mul]]
param = "jump_y"
subparam = ""
value = 2.0

[[param_float]]
param = "param_drcapsule"
subparam = "gravity_accel"
value = 0.0
kinds = ["mariod","mariod_drcapsule"]
slots = [0,1,2]

[[param_float]]
param = "param_drcapsule"
subparam = "angle"
value = 0.0
kinds = ["mariod","mariod_drcapsule"]
slots = [0,1,2]

[[param_float]]
param = "param_special_lw"
subparam = "buoyancy"
value = 4.0

[[param_float]]
param = "param_special_lw"
subparam = "buoyancy_max"
value = 4.0

[[param_int]]
param = "article_use_type"
value = 1
kinds = ["mariod_capsuleblock"]

[[param_int]]
param = "kirby_cant_copy"
value = 0

[[param_int]]
param = "villager_cant_pocket"
subparam = "mariod_drcapsule"
value = 0